### ISSUE TITLE
bug with OCP 4.8.2 installed with assisted installer

### ISSUE THREAD

**Issue by hetzbh** [openshift/assisted-installer#348]
Hi,
I've used the assisted installer to install OpenShift 4.8.2 to a VM running on CentOS 8 using kvm - using the SNO method.
The installation process went fine, they were no errors and the monitor in cloud.redhat.com doesn't show anything.

I tried to test a simple thing. I should mention that the SNO method is the default, nothing has been changed or tweaked from the stock install.

I used the oc command to create a project and test rails-postgresql-example. It fails due to "but the administrator has not configured the integrated container image registry".

Here are the logs. Should I post it in bugzilla? (if so, under which component?)

```
$ oc new-project test124
Now using project "test124" on server "https://api.demo.hetzlabs.local:6443".

You can add applications to this project with the 'new-app' command. For example, try:

    oc new-app rails-postgresql-example

to build a new example application in Ruby. Or use kubectl to deploy a simple Kubernetes application:

    kubectl create deployment hello-node --image=k8s.gcr.io/serve_hostname

$ oc new-app rails-postgresql-example
--> Deploying template "openshift/rails-postgresql-example" to project test124

     Rails + PostgreSQL (Ephemeral)
     ---------
     An example Rails application with a PostgreSQL database. For more information about using this template, including OpenShift considerations, see https://github.com/sclorg/rails-ex/blob/master/README.md.
     
     WARNING: Any data stored will be lost upon pod destruction. Only use this template for testing.

     The following service(s) have been created in your project: rails-postgresql-example, postgresql.
     
     For more information about using this template, including OpenShift considerations, see https://github.com/sclorg/rails-ex/blob/master/README.md.

     * With parameters:
        * Name=rails-postgresql-example
        * Namespace=openshift
        * Memory Limit=512Mi
        * Memory Limit (PostgreSQL)=512Mi
        * Git Repository URL=https://github.com/sclorg/rails-ex.git
        * Git Reference=
        * Context Directory=
        * Application Hostname=
        * GitHub Webhook Secret=4cker8Iaya8IYMaKAcb5mIx5b5jy23yyHexlthkN # generated
        * Secret Key=4xngxigktgwccawjm8vx2u16u3j7heq1n7xuhccwwdhhx64vuga5o7f7d45n6fx8ooyexkub65qetedgm2kn0nc7onkx7tdgsbdkh4x3oehhj5m7jyjrx0w7rpon61o # generated
        * Application Username=openshift
        * Application Password=secret
        * Rails Environment=production
        * Database Service Name=postgresql
        * Database Username=userNMR # generated
        * Database Password=T47h18Ne # generated
        * Database Name=root
        * Maximum Database Connections=100
        * Shared Buffer Amount=12MB
        * Custom RubyGems Mirror URL=

--> Creating resources ...
    secret "rails-postgresql-example" created
    service "rails-postgresql-example" created
    route.route.openshift.io "rails-postgresql-example" created
    imagestream.image.openshift.io "rails-postgresql-example" created
    buildconfig.build.openshift.io "rails-postgresql-example" created
    deploymentconfig.apps.openshift.io "rails-postgresql-example" created
    service "postgresql" created
    deploymentconfig.apps.openshift.io "postgresql" created
--> Success
    Access your application via route 'rails-postgresql-example-test124.apps.demo.hetzlabs.local' 
    WARNING: No container image registry has been configured with the server. Automatic builds and deployments may not function.
    Build scheduled, use 'oc logs -f buildconfig/rails-postgresql-example' to track its progress.
    Run 'oc status' to view your app.

$ oc status
In project test124 on server https://api.demo.hetzlabs.local:6443

svc/postgresql - 172.30.147.134:5432
  dc/postgresql deploys openshift/postgresql:12-el8 
    deployment #1 deployed 3 minutes ago - 1 pod

http://rails-postgresql-example-test124.apps.demo.hetzlabs.local (svc/rails-postgresql-example)
  dc/rails-postgresql-example deploys istag/rails-postgresql-example:latest <-
    bc/rails-postgresql-example source builds https://github.com/sclorg/rails-ex.git on openshift/ruby:2.6-ubi8 
      build #1 new for 3 minutes (can't push to image)
    deployment #1 waiting on image or update

Errors:
  * bc/rails-postgresql-example is pushing to istag/rails-postgresql-example:latest, but the administrator has not configured the integrated container image registry.

1 error identified, use 'oc status --suggest' to see details.
```

I'm sure there is a simple fix for that, but I think it should be fixed in RH's OCP IMHO...

**Comment by hetzbh** [comment]
Looks like it's not a bug but it's on purpose.
The questrion is - since SNO is not for production, why not set the registry by default to EmptyDir??

**Comment by ryannix123** [comment]
@hetzbh That's considered a "Day 2 operation". You can set your own storage class or simply run these commands as Kubeadmin:

`oc patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{"spec":{"managementState":"Managed"}}'
`oc patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{"spec":{"storage":{"emptyDir":{}}}}'

**Comment by hetzbh** [comment]
@ryannix123 you're absolutely right, but my question is simple: why not enable it by default when the installer installs and configure the system, so the user can use the machine right away? if he/she needs a permanent storage, he should see a link where to enable it and how..

**Comment by ryannix123** [comment]
Maybe we can add an RFE for that feature. i.e., either add some instructions to the page for storage post-installation or see what we can do to run those commands post-install, which I think would only be mostly appropriate for instances of Single Node OpenShift.

**Comment by romfreiman** [comment]
https://docs.openshift.com/container-platform/4.8/installing/installing_bare_metal/installing-bare-metal.html#installation-registry-storage-config_installing-bare-metal

**Comment by romfreiman** [comment]
It has nothing to do with SNO. This behavior is similar to all deployments without built in storage provider (baremetal /  upi).

**Comment by hetzbh** [comment]
@romfreiman I know, but yet, the SNO is a different beast. People who are new to Openshift would love to install it and not CRC for example, since CRC by default doesn't allow accesss/view apps remotely and SNO allows that.

**Comment by ryannix123** [comment]
@romfreiman I agree with @hetzbh in that SNO is a kind of nuanced deployment used for labs or even edge test cases. It would be great to add those instructions to the page as a "FYI".

**Comment by romfreiman** [comment]
good point. We might want to add it as a checkbox to the Assisted Installer (and then make it preconfigured to EmptyDir)

**Comment by romfreiman** [comment]
Feel free to contribute BTW :)

**Comment by ryannix123** [comment]
Absolutely, I'll help wherever I can. :) I think A.I. is fantastic, and I think SNO is especially exciting.

**Comment by romfreiman** [comment]
Thanks for the feedback.
So you basically can add a flag to the api to configure local registry, and in case it's selected, inject emptyDir manifest. :)

**Comment by eranco74** [comment]
> Looks like it's not a bug but it's on purpose.
> The questrion is - since SNO is not for production, why not set the registry by default to EmptyDir??
Note that SNO aim to be single-node **production** OpenShift  (for specific use cases).
https://github.com/openshift/enhancements/blob/master/enhancements/single-node/production-deployment-approach.md 
Other than emptyDir you could mark the LSO checkbox in assisted-installer UI.

**Comment by hetzbh** [comment]
@eranco74 additional disk? Where? I didn't see it as a requirement or something that the installer uses it for storage...

**Comment by eranco74** [comment]
I mean that instead of using emptyDir you could use local storage operator (LSO).
Deploying SNO with LSO is already supported in assisted-installer (it's not the default though).
LSO requires a disk for provisioning.
https://docs.openshift.com/container-platform/4.7/storage/persistent_storage/persistent-storage-local.html

**Comment by hetzbh** [comment]
I see, but I don't see where the SNO supports LSO, and it doesn't mentioned at all in the requirement popup (as an option or not).
Of course, if SNO could detect /dev/sdb (or /dev/vdb) existence and could create the LSO automatically - it would be the best.
BTW - thanks for the link. I think the OCP docs needs some special section for SNO.

**Comment by eranco74** [comment]
In any case, for kicking the tires, emptyDir is easier.

**Comment by hetzbh** [comment]
BTW, I'm going to record a video (in Hebrew) about SNO, feel free to check it later at [my channel](https://www.youtube.com/channel/UCWrtPbXo4iVxO45aRABIJjg) ;)

**Comment by eranco74** [comment]
SNO support LSO just like it support any other operator.
Configuring LSO is considered a day 2 operation but the assisted-installer provided that functionality at day one (as opt in, I guess it's not in prod yet and that's why you didn't see it).
You can get some more info about SNO and the assisted installer [here](https://cloud.redhat.com/blog/deploy-openshift-at-the-edge-with-single-node-openshift) :wink:

**Comment by hetzbh** [comment]
Well, I just finished spending few hours with the assisted installer beta. I tried setting up a VM with 2 disks (each 200GB) and yet, it didn't create any LSO automatically.

**Comment by eranco74** [comment]
As I said above, LSO is an opt-in and isn't exposed (for SNO) in the assisted installer UI yet.
