### ISSUE TITLE
serious bug with SNO?

### ISSUE THREAD

**Issue by hetzbh** [openshift/assisted-installer#349]
Hi,
I've reinstalled SNO on a VM today from scratch. Installation went without a problem.

However, I see 2 weird things compared to yesterday:

1. When trying to deploy any sample app (sample Python basic for example), I get the following in the log stream:
```
Cloning "https://github.com/elsony/devfile-sample-python-basic.git" ...
error: fatal: unable to access 'https://github.com/elsony/devfile-sample-python-basic.git/': SSL certificate problem: self signed certificate in certificate chain
```

2. Clicking on "add" and selecting "All services" - I only get 4 services (Basic NodeJS, Basic Python, Basic Quarkus, Basic Spring boot) and only Devfile type. There are no other items in the catalog.

Should I open a bug in BZ about it?

**Comment by eranco74** [comment]
Unsure what went wrong, I just tried it myself and it seems to be working.
I see 14 sample apps, and the python-basic example is running:
 Build log:
 ```
 Cloning "https://github.com/elsony/devfile-sample-python-basic.git" ...
	Commit:	de421f7a7fdcde306415a71ed7d719fb0f7bf8ee (Optimze build)
	Author:	eyuen <eyuen@redhat.com>
	Date:	Fri Apr 30 15:30:14 2021 -0400
time="2021-09-09T13:22:44Z" level=info msg="Not using native diff for overlay, this may cause degraded performance for building images: kernel has CONFIG_OVERLAY_FS_REDIRECT_DIR enabled"
I0909 13:22:44.226242       1 defaults.go:102] Defaulting to storage driver "overlay" with options [mountopt=metacopy=on].
Caching blobs under "/var/cache/blobs".

Pulling image python:slim ...

Successfully pushed image-registry.openshift-image-registry.svc:5000/new/python-basic@sha256:ca028d9efb88e3e189e3ad28bf15ab0e2a0e0188ded6853092203c01c7b9492d
Push successful
```

Pod logs:
INFO:waitress:Serving on http://0.0.0.0:8081
