### ISSUE TITLE
Which doc is right?

### ISSUE THREAD

**Issue by hetzbh** [openshift/assisted-installer#429]
Looking at the instructions in Redhat's cloud page after creating a SNO install, it asks the user to create 3 records in their DNS server: api, api-int, and a wildcard *.apps.<cluster_ID>.

However, looking at the OKD docs [here](https://docs.okd.io/latest/installing/installing_sno/install-sno-preparing-to-install-sno.html), at the bottom of the page, it looks there's a 4th records. I don't see it mentioned in cloud.redhat.com pages.

So which one is right and how do I contact the docs team to fix it?

Thanks

**Comment by romfreiman** [comment]
AFAIK honstnames DNS is not needed anymore

**Comment by hetzbh** [comment]
Ok, I asked the docs team to fix this issue. Thanks for your help ;)
